search:
  audit_sites:
    federal:
      - oig.hhs.gov
      - gao.gov
      - cms.gov
      - medicaid.gov
    state:
      - auditor.illinois.gov
      - auditor.ca.gov
      - sao.texas.gov
      - auditor.mo.gov
      - audits.ga.gov
      - sao.wa.gov
      - auditor.nebraska.gov
      - osa.state.ms.us
      - auditor.state.oh.us
      - oag.state.ny.us
    # Additional sites for broader coverage
    extended:
      - oig.treasury.gov
      - oig.justice.gov
      - recovery.gov
      - osa.georgia.gov
      - auditors.ohio.gov
      - osa.state.la.us
      - osa.arkansas.gov
      - sao.state.ia.us
      - auditor.utah.gov
      - osa.state.ok.us
      - osa.ks.gov
      - auditor.sd.gov
      - sao.nd.gov
      - auditor.mt.gov
      - auditor.wy.gov
      - auditor.co.gov
      - auditor.nm.gov
      - azauditor.gov
      - auditor.nv.gov
      - auditor.idaho.gov
      - sos.oregon.gov
      - auditor.alaska.gov
      - auditor.hawaii.gov


  output:
    date_format: "%Y-%m-%d_%H%M%S"

classifier:
  provider: "openai"  # "openai" or "gemini"
  model: "gpt-4.1-nano"  # Using existing GPT nano model from ai_extraction.py
  show_errors: true
  retry_attempts: 2
  batch_size: 5         # Number of items to process per batch
  batch_delay: 0.5      # Seconds to wait between batches