  search:
  audit_sites:
    federal:
      - oig.hhs.gov
      - gao.gov
      - cms.gov
      - medicaid.gov
    state:
      - auditor.illinois.gov
      - auditor.ca.gov
      - sao.texas.gov
      - auditor.mo.gov
      - sao.wa.gov
      - auditor.nebraska.gov
      - osa.state.ms.us
      - ohioauditor.gov
      - osc.state.ny.us
      - lla.la.gov
      - arklegaudit.gov
      - auditor.iowa.gov
      - auditor.utah.gov
      - sai.ok.gov
      - kslpa.ks.gov
      - auditor.sd.gov
      - ndauditor.gov
      - leg.mt.gov
      - sao.wyo.gov
      - leg.colorado.gov
      - saonm.org
      - azauditor.gov
      - leg.state.nv.us
      - legislature.idaho.gov
      - sos.oregon.gov
      - akleg.gov
      - auditor.hawaii.gov


  output:
    date_format: "%Y-%m-%d_%H%M%S"

  classifier:
    provider: "openai"  # "openai" or "gemini"
    model: "gpt-4.1-nano"  # Using existing GPT nano model from ai_extraction.py
    show_errors: true
    retry_attempts: 2
    batch_size: 5         # Number of items to process per batch
    batch_delay: 0.5      # Seconds to wait between batches