INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Single audits', 'single-audits', 'Single audits');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Collaboration', 'collaboration', 'Collaboration');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Audit trends', 'audit-trends', 'Audit trends');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Medicaid oversight', 'medicaid-oversight', 'Medicaid oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('concurrent enrollment', 'concurrent-enrollment', 'concurrent enrollment');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Ohio Medicaid', 'ohio-medicaid', 'Ohio Medicaid');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('capitation payments', 'capitation-payments', 'capitation payments');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('residency verification', 'residency-verification', 'residency verification');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('PARIS system', 'paris-system', 'PARIS system');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('interstate data match', 'interstate-data-match', 'interstate data match');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('public funds waste', 'public-funds-waste', 'public funds waste');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('state residency', 'state-residency', 'state residency');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('healthcare fraud', 'healthcare-fraud', 'healthcare fraud');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Recovery Audit Contractor', 'recovery-audit-contractor', 'Recovery Audit Contractor');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('CMS oversight', 'cms-oversight', 'CMS oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('managed care', 'managed-care', 'managed care');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('State exemptions', 'state-exemptions', 'State exemptions');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('SPAs', 'spas', 'SPAs');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Cost-effectiveness', 'cost-effectiveness', 'Cost-effectiveness');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Overpayment recovery', 'overpayment-recovery', 'Overpayment recovery');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Oregon', 'oregon', 'Oregon');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('CCOs', 'ccos', 'CCOs');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('federal regulations', 'federal-regulations', 'federal regulations');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('healthcare costs', 'healthcare-costs', 'healthcare costs');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Third-Party Vendors', 'third-party-vendors', 'Third-Party Vendors');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('provider incentives', 'provider-incentives', 'provider incentives');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Special Payments', 'special-payments', 'Special Payments');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Program Integrity', 'program-integrity', 'Program Integrity');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Transportation Services', 'transportation-services', 'Transportation Services');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Documentation', 'documentation', 'Documentation');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Medical Necessity', 'medical-necessity', 'Medical Necessity');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Billing Irregularities', 'billing-irregularities', 'Billing Irregularities');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Fraud', 'fraud', 'Fraud');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('compliance', 'compliance', 'compliance');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Provider Agreement', 'provider-agreement', 'Provider Agreement');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Recipient Eligibility', 'recipient-eligibility', 'Recipient Eligibility');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Managed Care Organizations', 'managed-care-organizations', 'Managed Care Organizations');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('encounter data', 'encounter-data', 'encounter data');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('data analytics', 'data-analytics', 'data analytics');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Overpayment recovery', 'overpayment-recovery', 'Overpayment recovery');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Premium Rates', 'Premium-Rates', 'Premium Rates');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('HCA Oversight', 'HCA-Oversight', 'HCA Oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Data Quality', 'data-quality', 'Data Quality');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Immigrant Seniors', 'immigrant-seniors', 'Immigrant Seniors');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('HBIS', 'hbis', 'HBIS');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('HBIA', 'hbia', 'HBIA');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Enrollment Data', 'enrollment-data', 'Enrollment Data');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Program Costs', 'program-costs', 'Program Costs');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Eligibility Verification', 'eligibility-verification', 'Eligibility Verification');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Redetermination', 'redetermination', 'Redetermination');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Federal Reimbursement', 'federal-reimbursement', 'Federal Reimbursement');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('EVV', 'evv', 'EVV');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Home Health Services', 'home-health-services', 'Home Health Services');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Personal Care Services', 'personal-care-services', 'Personal Care Services');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Claims Data', 'claims-data', 'Claims Data');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Provider Compliance', 'provider-compliance', 'Provider Compliance');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Stakeholder Engagement', 'stakeholder-engagement', 'Stakeholder Engagement');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Technology Implementation', 'technology-implementation', 'Technology Implementation');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Data Matching', 'data-matching', 'Data Matching');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('capitation payments', 'capitation-payments', 'capitation payments');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Medical Loss Ratio', 'medical-loss-ratio', 'Medical Loss Ratio');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Duplicate Payments', 'duplicate-payments', 'Duplicate Payments');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Health Insurer Fee', 'health-insurer-fee', 'Health Insurer Fee');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Gross-up Payments', 'gross-up-payments', 'Gross-up Payments');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Denial Rates', 'denial-rates', 'Denial Rates');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('oversight', 'oversight', 'oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Payment Risks', 'payment-risks', 'Payment Risks');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('CMS oversight', 'cms-oversight', 'CMS oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('mco', 'mco', 'mco');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Capitation Rates', 'capitation-rates', 'Capitation Rates');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Fraud Detection', 'fraud-detection', 'Fraud Detection');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Audit Delays', 'audit-delays', 'Audit Delays');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Reimbursements', 'reimbursements', 'Reimbursements');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Billing Errors', 'billing-errors', 'Billing Errors');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Nursing Facility', 'nursing-facility', 'Nursing Facility');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Therapy Services', 'therapy-services', 'Therapy Services');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Overpayment', 'overpayment', 'Overpayment');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Ohio Department of Job and Family Services', 'ohio-department-of-job-and-family-services', 'Ohio Department of Job and Family Services');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Room and Board', 'room-and-board', 'Room and Board');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Billing Compliance', 'billing-compliance', 'Billing Compliance');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Audit findings', 'audit-findings', 'Audit findings');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Senate Bill 894', 'senate-bill-894', 'Senate Bill 894');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Audit Processes', 'audit-processes', 'Audit Processes');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Performance Audits', 'performance-audits', 'Performance Audits');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Rebates', 'rebates', 'Rebates');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('External Quality Review Organization', 'external-quality-review-organization', 'External Quality Review Organization');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('IT Controls', 'it-controls', 'IT Controls');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Contract Oversight', 'contract-oversight', 'Contract Oversight');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Dispute Resolution', 'dispute-resolution', 'Dispute Resolution');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Medicare', 'medicare', 'Medicare');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Provider Screening', 'provider-screening', 'Provider Screening');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Adult Care Facilities', 'Adult-Care-Facilities', 'Adult Care Facilities');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Department of Health', 'Department-of-Health', 'Department of Health');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('inspections', 'inspections', 'inspections');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Complaint Investigations', 'Complaint-Investigations', 'Complaint Investigations');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Resident Safety', 'Resident-Safety', 'Resident Safety');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Regulatory Compliance', 'Regulatory-Compliance', 'Regulatory Compliance');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Follow-up Actions', 'Follow-up-Actions', 'Follow-up Actions');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Data Management', 'Data-Management', 'Data Management');
INSERT INTO keyword_mappings (canonical_keyword, slug, variation) VALUES ('Staffing Shortages', 'Staffing-Shortages', 'Staffing Shortages');
